[project]
authors = ["Simon Thalén <thalen.simon@gmail.com>"]
channels = ["conda-forge"]
name = "cine_to_gif"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.7,<3.14"
pydicom = ">=3.0.1,<4"
matplotlib = ">=3.10.6,<4"
ipykernel = ">=6.30.1,<7"
imageio = ">=2.37.0,<3"
